import type { FactorDef } from "./types.js";
import { indexById } from "./registry-utils.js";

export const factorRegistry = [
  {
    id: "forecast-consensus-anchor",
    label: "Forecast consensus",
    category: "internal",
    domain: "forecasts",
    description:
      "Definition-matched crowd and market expectations that set the baseline anchor before live factors move it.",
    sources: ["metaculus-agi-questions", "manifold-ai-markets", "polymarket-ai"],
    normalization: "zscore",
    sign: 1,
    weight: 8,
    cadence: "hourly",
    bounds: {
      min: 0,
      max: 1,
    },
  },
  {
    id: "frontier-benchmark-saturation",
    label: "Frontier benchmark saturation",
    category: "internal",
    domain: "benchmarks",
    description:
      "Composite saturation across frontier benchmark leaderboards, tracked separately from the date estimate.",
    sources: [
      "papers-with-code-leaderboards",
      "lmarena-leaderboard",
      "arc-prize",
      "helm-crfm",
      "stanford-ai-index",
    ],
    normalization: "momentum-01",
    sign: 1,
    weight: 7,
    cadence: "daily",
    bounds: {
      min: 0,
      max: 1,
    },
  },
  {
    id: "training-compute-growth",
    label: "Training compute growth",
    category: "internal",
    domain: "compute",
    description:
      "Growth in frontier training compute and related scaling indicators.",
    sources: ["epoch-ai-notable-models"],
    normalization: "log-zscore",
    sign: 1,
    weight: 6,
    cadence: "weekly",
    transform: "log10",
    bounds: {
      min: 0,
    },
  },
  {
    id: "research-velocity",
    label: "Research velocity",
    category: "internal",
    domain: "research",
    description:
      "AI research output and citation momentum from structured paper feeds.",
    sources: ["arxiv-ai-paper-volume", "semantic-scholar", "github-frontier"],
    normalization: "zscore",
    sign: 1,
    weight: 3,
    cadence: "daily",
    bounds: {
      min: 0,
    },
  },
  {
    id: "adoption-usage",
    label: "Adoption and usage",
    category: "internal",
    domain: "adoption",
    description:
      "Public model usage, downloads, and deployment proxies from structured usage feeds.",
    sources: ["openrouter-usage", "hugging-face-hub"],
    normalization: "momentum-01",
    sign: 1,
    weight: 5,
    cadence: "daily",
    bounds: {
      min: 0,
      max: 1,
    },
  },
  {
    id: "datacenter-capex",
    label: "Datacenter capex",
    category: "internal",
    domain: "economics",
    description:
      "Investment and revenue signals that proxy buildout capacity for frontier systems.",
    sources: ["hyperscaler-ir", "nvidia-earnings", "fred-macro"],
    normalization: "log-zscore",
    sign: 1,
    weight: 4,
    cadence: "monthly",
    transform: "log10",
    bounds: {
      min: 0,
    },
  },
  {
    id: "energy-headroom",
    label: "Energy & grid constraints",
    category: "external",
    domain: "energy",
    description:
      "Electricity supply and grid limits on datacenter buildout — a higher reading means a tighter constraint (more drag on the date).",
    sources: ["eia-electricity", "ember-electricity", "iea-energy"],
    normalization: "zscore",
    sign: -1,
    weight: 5,
    cadence: "weekly",
    bounds: {
      min: 0,
      max: 1,
    },
  },
  {
    id: "policy-friction",
    label: "Policy friction",
    category: "external",
    domain: "policy",
    description:
      "Regulatory and governance pressure that can slow deployment or constrain scaling.",
    sources: ["oecd-ai-policy", "nist-ai-risk"],
    normalization: "momentum-01",
    sign: -1,
    weight: 4,
    cadence: "weekly",
    bounds: {
      min: 0,
      max: 1,
    },
  },
  {
    id: "public-backlash-pressure",
    label: "Public backlash pressure",
    category: "external",
    domain: "sentiment",
    description:
      "News tone and public pressure that can create deployment drag.",
    sources: ["gdelt-ai-tone", "pew-ai-sentiment"],
    normalization: "zscore",
    sign: -1,
    weight: 3,
    cadence: "hourly",
    bounds: {
      min: 0,
      max: 1,
    },
  },
  {
    id: "labor-automation-exposure",
    label: "Labor automation exposure",
    category: "external",
    domain: "jobs",
    description:
      "Occupation-level exposure and automation signals for broad economic deployment.",
    sources: ["onet-occupation-data", "anthropic-economic-index"],
    normalization: "momentum-01",
    sign: 1,
    weight: 4,
    cadence: "monthly",
    bounds: {
      min: 0,
      max: 1,
    },
  },
  {
    id: "autonomy-horizon",
    label: "Autonomy horizon",
    category: "internal",
    domain: "autonomy",
    description:
      "Length of tasks frontier agents can complete autonomously (METR task-horizon doubling).",
    sources: ["metr-autonomy"],
    normalization: "momentum-01",
    sign: 1,
    weight: 6,
    cadence: "monthly",
    bounds: { min: 0, max: 1 },
  },
  {
    id: "algorithmic-efficiency",
    label: "Algorithmic efficiency",
    category: "internal",
    domain: "compute",
    description:
      "Improvement in capability per unit of compute (algorithmic progress doubling).",
    sources: ["stanford-ai-index"],
    normalization: "momentum-01",
    sign: 1,
    weight: 4,
    cadence: "monthly",
    bounds: { min: 0, max: 1 },
  },
  {
    id: "hardware-supply",
    label: "Hardware supply",
    category: "internal",
    domain: "hardware",
    description:
      "Advanced-node and accelerator supply growth that enables larger training runs.",
    sources: ["tsmc-capacity"],
    normalization: "momentum-01",
    sign: 1,
    weight: 4,
    cadence: "monthly",
    bounds: { min: 0, max: 1 },
  },
  {
    id: "export-control-friction",
    label: "Export-control friction",
    category: "external",
    domain: "hardware",
    description:
      "Chip export controls and supply restrictions that can slow frontier scaling.",
    sources: ["bis-export-controls"],
    normalization: "momentum-01",
    sign: -1,
    weight: 3,
    cadence: "monthly",
    bounds: { min: 0, max: 1 },
  },
  {
    id: "safety-eval-pressure",
    label: "Safety-eval pressure",
    category: "external",
    domain: "safety",
    description:
      "Dangerous-capability evaluations and safety gating that can add release friction.",
    sources: ["uk-aisi-evals"],
    normalization: "momentum-01",
    sign: -1,
    weight: 2,
    cadence: "monthly",
    bounds: { min: 0, max: 1 },
  },
  {
    id: "capital-formation",
    label: "AI capital formation",
    category: "internal",
    domain: "economics",
    description:
      "Private AI investment and frontier-lab funding momentum — the capital that finances larger training runs and deployment, distinct from hyperscaler capex. Now blended with live semiconductor-index momentum.",
    sources: ["ai-index-investment", "nasdaq-index"],
    normalization: "log-zscore",
    sign: 1,
    weight: 4,
    cadence: "monthly",
    bounds: { min: 0, max: 1 },
  },
  {
    id: "macro-headwinds",
    label: "Macro & bubble risk",
    category: "external",
    domain: "economics",
    description:
      "Recession risk, tightening financial conditions, and AI-bubble concerns that could throttle the buildout if capital pulls back. Blended with live FRED recession-probability when a key is set.",
    sources: ["macro-risk-index", "fred-recession"],
    normalization: "zscore",
    sign: -1,
    weight: 3,
    cadence: "weekly",
    bounds: { min: 0, max: 1 },
  },
  {
    id: "robotics-embodiment",
    label: "Robotics & embodiment",
    category: "internal",
    domain: "autonomy",
    description:
      "Progress in physical-world robotics and embodied agents — most relevant to robust, general autonomy (weighted heavily for Strong AGI).",
    sources: ["ifr-world-robotics"],
    normalization: "momentum-01",
    sign: 1,
    weight: 3,
    cadence: "monthly",
    bounds: { min: 0, max: 1 },
  },
  {
    id: "frontier-release-cadence",
    label: "Frontier release cadence",
    category: "internal",
    domain: "labs",
    description:
      "How fast frontier labs are shipping major models — release velocity over the last ~9 months, computed from real release dates (not a hand-set value).",
    sources: ["epoch-ai-notable-models"],
    normalization: "momentum-01",
    sign: 1,
    weight: 4,
    cadence: "daily",
    bounds: { min: 0, max: 1 },
  },
  {
    id: "data-availability",
    label: "Training-data scarcity",
    category: "internal",
    domain: "compute",
    description:
      "The 'data wall' — scarcity of high-quality training data that can slow further pre-training scaling. A higher reading means a tighter limit (more drag). Most relevant to the largest models.",
    sources: ["epoch-data-wall"],
    normalization: "momentum-01",
    sign: -1,
    weight: 3,
    cadence: "monthly",
    bounds: { min: 0, max: 1 },
  },
] as const satisfies readonly FactorDef[];

export const factorsById = indexById(factorRegistry);

export type FactorEntry = (typeof factorRegistry)[number];
export type FactorId = FactorEntry["id"];
