import type { SourceDef } from "./types.js";
import { indexById } from "./registry-utils.js";

export const sourceRegistry = [
  {
    id: "fixture-hourly-signals",
    name: "Fixture hourly signals",
    domain: "scaffold",
    accessMethod: "file",
    ingestion: "structured",
    authNeeded: false,
    cadence: "hourly",
    tosNotes: "Local deterministic scaffold data; not a production source.",
    parser: "fixture",
    url: "fixture://hourly-signals",
  },
  {
    id: "fixture-daily-signals",
    name: "Fixture daily signals",
    domain: "scaffold",
    accessMethod: "file",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    tosNotes: "Local deterministic scaffold data; not a production source.",
    parser: "fixture",
    url: "fixture://daily-signals",
  },
  {
    id: "fixture-weekly-signals",
    name: "Fixture weekly signals",
    domain: "scaffold",
    accessMethod: "file",
    ingestion: "structured",
    authNeeded: false,
    cadence: "weekly",
    tosNotes: "Local deterministic scaffold data; not a production source.",
    parser: "fixture",
    url: "fixture://weekly-signals",
  },
  {
    id: "metaculus-agi-questions",
    name: "Metaculus AGI questions",
    domain: "forecasts",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    rateLimit: "Use conservative unauthenticated request volume.",
    parser: "metaculus",
    url: "https://www.metaculus.com/api2/questions/",
  },
  {
    id: "manifold-ai-markets",
    name: "Manifold AI markets",
    domain: "forecasts",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "hourly",
    rateLimit: "Respect public API request guidance.",
    parser: "manifold",
    url: "https://api.manifold.markets/v0/markets",
  },
  {
    id: "epoch-ai-notable-models",
    name: "Epoch AI notable models",
    domain: "compute",
    accessMethod: "file",
    ingestion: "structured",
    authNeeded: false,
    cadence: "weekly",
    parser: "epoch-ai-notable-models",
    url: "https://epoch.ai/data/notable-ai-models",
  },
  {
    id: "papers-with-code-leaderboards",
    name: "Papers With Code leaderboards",
    domain: "benchmarks",
    accessMethod: "scrape",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    tosNotes: "Prefer official datasets or documented endpoints when available.",
    parser: "papers-with-code",
    url: "https://paperswithcode.com/sota",
  },
  {
    id: "lmarena-leaderboard",
    name: "LMArena leaderboard",
    domain: "benchmarks",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    parser: "lmarena",
    url: "https://lmarena.ai/",
  },
  {
    id: "arxiv-ai-paper-volume",
    name: "arXiv AI paper volume",
    domain: "research",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    rateLimit: "Follow arXiv API request pacing.",
    parser: "arxiv",
    url: "https://export.arxiv.org/api/query",
  },
  {
    id: "openrouter-usage",
    name: "OpenRouter model usage",
    domain: "adoption",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    parser: "openrouter",
    url: "https://openrouter.ai/",
  },
  {
    id: "hugging-face-hub",
    name: "Hugging Face Hub",
    domain: "adoption",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    rateLimit: "Use public Hub API responsibly; token optional for higher limits.",
    parser: "hugging-face",
    url: "https://huggingface.co/api/models",
  },
  {
    id: "hyperscaler-ir",
    name: "Hyperscaler investor relations",
    domain: "economics",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "curated-ir",
    url: "curated://hyperscaler-ir",
  },
  {
    id: "nvidia-earnings",
    name: "NVIDIA earnings",
    domain: "economics",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "curated-ir",
    url: "curated://nvidia-earnings",
  },
  {
    id: "eia-electricity",
    name: "EIA electricity data",
    domain: "energy",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: true,
    cadence: "weekly",
    rateLimit: "Free API key required; enforce key-specific limits.",
    parser: "eia",
    url: "https://api.eia.gov/v2/",
  },
  {
    id: "ember-electricity",
    name: "Ember electricity data",
    domain: "energy",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "weekly",
    parser: "ember",
    url: "https://ember-climate.org/data/",
  },
  {
    id: "oecd-ai-policy",
    name: "OECD.AI Policy Observatory",
    domain: "policy",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "weekly",
    parser: "oecd-ai",
    url: "https://oecd.ai/en/data",
  },
  {
    id: "nist-ai-risk",
    name: "NIST AI risk management guidance",
    domain: "policy",
    accessMethod: "feed",
    ingestion: "structured",
    authNeeded: false,
    cadence: "monthly",
    parser: "nist-feed",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
  },
  {
    id: "gdelt-ai-tone",
    name: "GDELT AI news tone",
    domain: "sentiment",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "hourly",
    rateLimit: "Batch requests and cache responses per run.",
    parser: "gdelt",
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
  },
  {
    id: "onet-occupation-data",
    name: "O*NET occupation data",
    domain: "jobs",
    accessMethod: "file",
    ingestion: "structured",
    authNeeded: false,
    cadence: "monthly",
    parser: "onet",
    url: "https://www.onetcenter.org/database.html",
  },
  {
    id: "anthropic-economic-index",
    name: "Anthropic Economic Index",
    domain: "jobs",
    accessMethod: "file",
    ingestion: "structured",
    authNeeded: false,
    cadence: "monthly",
    parser: "anthropic-economic-index",
    url: "https://www.anthropic.com/economic-index",
  },
] as const satisfies readonly SourceDef[];

export const sourcesById = indexById(sourceRegistry);

export type SourceEntry = (typeof sourceRegistry)[number];
export type SourceId = SourceEntry["id"];
