import type { SourceDef } from "./types.js";
import { indexById } from "./registry-utils.js";

export const sourceRegistry = [
  {
    id: "metaculus-agi-questions",
    name: "Metaculus AGI questions",
    domain: "forecasts",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    rateLimit: "Use conservative unauthenticated request volume.",
    parser: "metaculus",
    url: "https://www.metaculus.com/api2/questions/",
  },
  {
    id: "manifold-ai-markets",
    name: "Manifold AI markets",
    domain: "forecasts",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "hourly",
    rateLimit: "Respect public API request guidance.",
    parser: "manifold",
    url: "https://api.manifold.markets/v0/markets",
  },
  {
    id: "epoch-ai-notable-models",
    name: "Epoch AI notable models",
    domain: "compute",
    accessMethod: "file",
    ingestion: "structured",
    authNeeded: false,
    cadence: "weekly",
    parser: "epoch-ai-notable-models",
    url: "https://epoch.ai/data/notable-ai-models",
  },
  {
    id: "papers-with-code-leaderboards",
    name: "Papers With Code leaderboards",
    domain: "benchmarks",
    accessMethod: "scrape",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    tosNotes: "Prefer official datasets or documented endpoints when available.",
    parser: "papers-with-code",
    url: "https://paperswithcode.com/sota",
  },
  {
    id: "lmarena-leaderboard",
    name: "LMArena leaderboard",
    domain: "benchmarks",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    parser: "lmarena",
    url: "https://lmarena.ai/",
  },
  {
    id: "arxiv-ai-paper-volume",
    name: "arXiv AI paper volume",
    domain: "research",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    rateLimit: "Follow arXiv API request pacing.",
    parser: "arxiv",
    url: "https://export.arxiv.org/api/query",
  },
  {
    id: "openrouter-usage",
    name: "OpenRouter model usage",
    domain: "adoption",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    parser: "openrouter",
    url: "https://openrouter.ai/",
  },
  {
    id: "hugging-face-hub",
    name: "Hugging Face Hub",
    domain: "adoption",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "daily",
    rateLimit: "Use public Hub API responsibly; token optional for higher limits.",
    parser: "hugging-face",
    url: "https://huggingface.co/api/models",
  },
  {
    id: "hyperscaler-ir",
    name: "Hyperscaler investor relations",
    domain: "economics",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "curated-ir",
    url: "curated://hyperscaler-ir",
  },
  {
    id: "nvidia-earnings",
    name: "NVIDIA earnings",
    domain: "economics",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "curated-ir",
    url: "curated://nvidia-earnings",
  },
  {
    id: "eia-electricity",
    name: "EIA electricity data",
    domain: "energy",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: true,
    cadence: "weekly",
    rateLimit: "Free API key required; enforce key-specific limits.",
    parser: "eia",
    url: "https://api.eia.gov/v2/",
  },
  {
    id: "ember-electricity",
    name: "Ember electricity data",
    domain: "energy",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "weekly",
    parser: "ember",
    url: "https://ember-climate.org/data/",
  },
  {
    id: "oecd-ai-policy",
    name: "OECD.AI Policy Observatory",
    domain: "policy",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "weekly",
    parser: "oecd-ai",
    url: "https://oecd.ai/en/data",
  },
  {
    id: "nist-ai-risk",
    name: "NIST AI risk management guidance",
    domain: "policy",
    accessMethod: "feed",
    ingestion: "structured",
    authNeeded: false,
    cadence: "monthly",
    parser: "nist-feed",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
  },
  {
    id: "gdelt-ai-tone",
    name: "GDELT AI news tone",
    domain: "sentiment",
    accessMethod: "api",
    ingestion: "structured",
    authNeeded: false,
    cadence: "hourly",
    rateLimit: "Batch requests and cache responses per run.",
    parser: "gdelt",
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
  },
  {
    id: "onet-occupation-data",
    name: "O*NET occupation data",
    domain: "jobs",
    accessMethod: "file",
    ingestion: "structured",
    authNeeded: false,
    cadence: "monthly",
    parser: "onet",
    url: "https://www.onetcenter.org/database.html",
  },
  {
    id: "anthropic-economic-index",
    name: "Anthropic Economic Index",
    domain: "jobs",
    accessMethod: "file",
    ingestion: "structured",
    authNeeded: false,
    cadence: "monthly",
    parser: "anthropic-economic-index",
    url: "https://www.anthropic.com/economic-index",
  },
  {
    id: "stanford-ai-index",
    name: "Stanford HAI AI Index",
    domain: "benchmarks",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "stanford-ai-index",
    url: "https://aiindex.stanford.edu/report/",
  },
  {
    id: "arc-prize",
    name: "ARC Prize (ARC-AGI)",
    domain: "benchmarks",
    accessMethod: "scrape",
    ingestion: "curated",
    authNeeded: false,
    cadence: "weekly",
    parser: "arc-prize",
    url: "https://arcprize.org/leaderboard",
  },
  {
    id: "helm-crfm",
    name: "Stanford HELM",
    domain: "benchmarks",
    accessMethod: "scrape",
    ingestion: "curated",
    authNeeded: false,
    cadence: "weekly",
    parser: "helm",
    url: "https://crfm.stanford.edu/helm/",
  },
  {
    id: "metr-autonomy",
    name: "METR task-horizon evaluations",
    domain: "autonomy",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "metr",
    url: "https://metr.org/",
  },
  {
    id: "polymarket-ai",
    name: "Polymarket AI markets",
    domain: "forecasts",
    accessMethod: "api",
    ingestion: "curated",
    authNeeded: false,
    cadence: "daily",
    parser: "polymarket",
    url: "https://polymarket.com/markets/ai",
  },
  {
    id: "semantic-scholar",
    name: "Semantic Scholar (AI citations)",
    domain: "research",
    accessMethod: "api",
    ingestion: "curated",
    authNeeded: true,
    cadence: "weekly",
    parser: "semantic-scholar",
    url: "https://www.semanticscholar.org/",
  },
  {
    id: "github-frontier",
    name: "GitHub frontier-AI activity",
    domain: "research",
    accessMethod: "api",
    ingestion: "curated",
    authNeeded: false,
    cadence: "daily",
    parser: "github",
    url: "https://github.com/topics/llm",
  },
  {
    id: "iea-energy",
    name: "IEA electricity & datacenter outlook",
    domain: "energy",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "iea",
    url: "https://www.iea.org/reports/electricity-2025",
  },
  {
    id: "tsmc-capacity",
    name: "TSMC advanced-node capacity",
    domain: "hardware",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "tsmc",
    url: "https://investor.tsmc.com/english",
  },
  {
    id: "bis-export-controls",
    name: "US BIS export controls",
    domain: "hardware",
    accessMethod: "feed",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "bis",
    url: "https://www.bis.gov/",
  },
  {
    id: "eu-ai-act",
    name: "EU AI Act tracker",
    domain: "policy",
    accessMethod: "scrape",
    ingestion: "curated",
    authNeeded: false,
    cadence: "weekly",
    parser: "eu-ai-act",
    url: "https://artificialintelligenceact.eu/",
  },
  {
    id: "fred-macro",
    name: "FRED macro indicators",
    domain: "economics",
    accessMethod: "api",
    ingestion: "curated",
    authNeeded: true,
    cadence: "weekly",
    parser: "fred",
    url: "https://fred.stlouisfed.org/",
  },
  {
    id: "pew-ai-sentiment",
    name: "Pew Research AI attitudes",
    domain: "sentiment",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "pew",
    url: "https://www.pewresearch.org/topic/science/science-issues/artificial-intelligence/",
  },
  {
    id: "uk-aisi-evals",
    name: "UK AI Safety Institute evaluations",
    domain: "safety",
    accessMethod: "file",
    ingestion: "curated",
    authNeeded: false,
    cadence: "monthly",
    parser: "aisi",
    url: "https://www.aisi.gov.uk/",
  },
] as const satisfies readonly SourceDef[];

export const sourcesById = indexById(sourceRegistry);

export type SourceEntry = (typeof sourceRegistry)[number];
export type SourceId = SourceEntry["id"];
